services:
  php:
    build:
      context: ./ubys-backend
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./ubys-backend:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_CONNECTION: mongodb
      APP_DEBUG: "false"
      DB_URI: 'mongodb://admin:admin!@72.61.136.135:27017/?authSource=admin&directConnection=true&serverSelectionTimeoutMS=3000&connectTimeoutMS=3000&socketTimeoutMS=8000'
      DB_DATABASE: ubys
    command: ["sh", "./docker/php/entrypoint.sh", "php-fpm"]
    networks:
      - ubys-network

  nginx:
    image: nginx:alpine
    ports:
      - "8001:8000"
    volumes:
      - ./ubys-backend:/var/www/html
      - ./ubys-backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ubys-network

  frontend:
    build:
      context: ./ubys-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      BACKEND_URL: 'http://nginx:8000'
    depends_on:
      - nginx
    networks:
      - ubys-network

  ngrok:
    image: ngrok/ngrok:latest
    command: http frontend:4000 --log=stdout
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
    depends_on:
      - frontend
    networks:
      - ubys-network

networks:
  ubys-network:
    driver: bridge
