services:
  backend:
    build:
      context: ./ubys-backend
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./ubys-backend:/var/www/html
    ports:
      - "8001:8000"
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      DB_CONNECTION: mongodb
      DB_URI: 'mongodb://admin:admin!@72.61.136.135:27017/?authSource=admin'
      DB_DATABASE: ubys_backend
    command: ["sh", "./docker/php/entrypoint.sh", "php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    networks:
      - ubys-network

  frontend:
    build:
      context: ./ubys-frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    depends_on:
      - backend
    networks:
      - ubys-network

networks:
  ubys-network:
    driver: bridge
